### ISSUE TITLE
`cachix use` overwrites globally configured substituters

### ISSUE THREAD

**Issue by Kha** [cachix/cachix#413]
I have a GH Actions workflow where I'm trying to configure a local binary cache restored from actions/cache, as that is quite a bit faster than always querying Cachix:
```
      - uses: cachix/install-nix-action@v15
        with:
          extra_nix_config: |
            extra-substituters = file://${{ github.workspace }}/nix-store-cache-copy?priority=10&trusted=true
      - uses: cachix/cachix-action@v10
        with: ...
```
However, despite the use of `extra-substituters`, it looks like Cachix' config in `~/.config/nix/nix.conf` completely replaces the above config:
```
+ cat /home/runner/.config/nix/nix.conf
substituters = https://cache.nixos.org https://lean4.cachix.or
trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= lean4.cachix.org-1:mawtxSxcaiWE24xCXXgh3qnvlTkyU7evRRnGeAhD4Wk=
+ nix show-config
...
substituters = https://cache.nixos.org https://lean4.cachix.org
```
Presumably this would be avoided if Cachix used `extra-substituters` as well.
