### ISSUE TITLE
Observing a "does not appear to be a binary cache" problem with Nix 2.10

### ISSUE THREAD

**Issue by Technius** [cachix/cachix#418]
I work on a project that uses `cachix-action` and a private binary cache for CI, and it has been working really well. Today, I observed some problems where the cache was not being picked up, specifically the "warning: XXX does not appear to be a binary cache" message. After some debugging, I noticed that `install-nix-action` was installing Nix 2.10 -- which was really unexpected because I didn't know it came out today just a few hours ago! The problem went away after the nix version was pinned to 2.9.2.

I'm not sure whether this is a problem with Nix, cachix, or cachix-action, so I'd be happy to post this issue in a more appropriate place.

For reference, here is a version of the workflow file modified to remove any sensitive information:
```yaml
name: My workflow
on:
  push:
    branches: [ main ]

jobs:
  build-expensive-dependency:
    runs-on: ubuntu-latest
    timeout-minutes: 300
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: cachix/install-nix-action@v17
        # the following two lines are used to workaround the problem
        with:
          install_url: https://releases.nixos.org/nix/nix-2.9.2/install
      - uses: cachix/cachix-action@v10
        with:
          name: my-private-cache-name
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: "Build and cache a dependency that is expensive to build"
        run: |
          nix -- build --print-build-logs .#my-expensive-dependency
```
