### ISSUE TITLE
Sometimes `cachix watch-exec` fails with `cachix: <<loop>>`

### ISSUE THREAD

**Issue by exarkun** [cachix/cachix#655]
**Describe the bug**

Sometimes a CircleCI step fails with a final line of output:

```
cachix: <<loop>>
```

The `cachix watch-exec ...` command exits with non-zero status failing the CI job.  The final built object _does_ appear to arrive at the cache (although it could also be that some later interaction added it, not the failing interaction - I'm not sure).

The CircleCI configuration is like (with simplifications and the real cache name elided):

```
jobs:
  build:
    docker:
      - image: "nixos/nix:2.22.1"

    environment:
      NIX_CONFIG: |
        experimental-features = nix-command flakes
        accept-flake-config = true

      CACHIX_NAME: "..."

    steps:
      - checkout
      - run:
          name: "Set up Caching"
          command: |
            NIXPKGS="nixpkgs/nixos-24.05"
            nix profile install --impure $NIXPKGS#cachix
            cachix --version
            cachix use "${CACHIX_NAME}"
      - run:
          name: "Build & Test"
          command: |
            # Run the build with cachix watching so that any outputs are
            # automatically sent to the cache.
            cachix watch-exec "${CACHIX_NAME}" -- nix build .#pkg-junit-xml --print-build-logs

      - run:
          name: "Docs"
          command: |
            cachix watch-exec "${CACHIX_NAME}" -- nix build .#pkg.doc --print-build-logs
```

The flake inputs are

```
Inputs:
├───agenix: github:ryantm/agenix/8d37c5bdeade12b6479c85acd133063ab53187a0?narHash=sha256-2T7CHTqBXJJ3ZC6R/4TXTcKoXWHcvubKNj9SfomURnw%3D (2024-05-09 21:32:35)
│   ├───darwin: github:lnl7/nix-darwin/4b9b83d5a92e8c1fbfd8eb27eda375908c11ec4d?narHash=sha256-gzGLZSiOhf155FW7262kdHo2YDeugp3VuIFb4/GGng0%3D (2023-11-24 03:11:34)
│   │   └───nixpkgs follows input 'agenix/nixpkgs'
│   ├───home-manager: github:nix-community/home-manager/3bfaacf46133c037bb356193bd2f1765d9dc82c1?narHash=sha256-7ulcXOk63TIT2lVDSExj7XzFx09LpdSAPtvgtM7yQPE%3D (2023-12-20 23:00:17)
│   │   └───nixpkgs follows input 'agenix/nixpkgs'
│   ├───nixpkgs: github:NixOS/nixpkgs/54aac082a4d9bb5bbc5c4e899603abfb76a3f6d6?narHash=sha256-%2BtFNwMvlXLbJZXiMHqYq77z/RfmpfpiI3yjL6o/Zo9M%3D (2023-12-19 19:15:32)
│   └───systems: github:nix-systems/default/da67096a3b9bf56a91d16901293e51ba5b49a27e?narHash=sha256-Vy1rq5AaRuLzOxct8nz4T6wlgyUR7zLU309k9mBC768%3D (2023-04-09 08:27:08)
├───flake-parts: github:hercules-ci/flake-parts/e5d10a24b66c3ea8f150e47dfdb0416ab7c3390e?narHash=sha256-yzcRNDoyVP7%2BSCNX0wmuDju1NUCt8Dz9%2BlyUXEI0dbI%3D (2024-05-02 09:10:30)
│   └───nixpkgs-lib: https://github.com/NixOS/nixpkgs/archive/50eb7ecf4cd0a5756d7275c8ba36790e5bd53e33.tar.gz?narHash=sha256-QBx10%2Bk6JWz6u7VsohfSw8g8hjdBZEf8CFzXH1/1Z94%3D (2024-05-02 09:00:52)
├───nixpkgs: github:NixOS/nixpkgs/2057814051972fa1453ddfb0d98badbea9b83c06?narHash=sha256-5ZSVkFadZbFP1THataCaSf0JH2cAH3S29hU9rrxTEqk%3D (2024-05-12 17:21:43)
└───pre-commit-hooks: github:cachix/pre-commit-hooks.nix/c182c876690380f8d3b9557c4609472ebfa1b141?narHash=sha256-/5u29K0c%2B4jyQ8x7dUIEUWlz2BoTSZWUP2quPwFCE7M%3D (2024-05-13 14:15:11)
    ├───flake-compat: github:edolstra/flake-compat/0f9255e01c2351cc7d116c072cb317785dd33b33?narHash=sha256-kvjfFW7WAETZlt09AgDn1MrtKzP7t90Vf7vypd3OL1U%3D (2023-10-04 13:37:54)
    ├───flake-utils: github:numtide/flake-utils/b1d9ab70662946ef0850d488da1c9019f3a9752a?narHash=sha256-SZ5L6eA7HJ/nmkzGG7/ISclqe6oZdOZTNoesiInkXPQ%3D (2024-03-11 08:33:50)
    │   └───systems: github:nix-systems/default/da67096a3b9bf56a91d16901293e51ba5b49a27e?narHash=sha256-Vy1rq5AaRuLzOxct8nz4T6wlgyUR7zLU309k9mBC768%3D (2023-04-09 08:27:08)
    ├───gitignore: github:hercules-ci/gitignore.nix/637db329424fd7e46cf4185293b9cc8c88c95394?narHash=sha256-HG2cCnktfHsKV0s4XW83gU3F57gaTljL9KNSuG6bnQs%3D (2024-02-28 02:28:52)
    │   └───nixpkgs follows input 'pre-commit-hooks/nixpkgs'
    ├───nixpkgs: github:NixOS/nixpkgs/e367f7a1fb93137af22a3908f00b9a35e2d286a7?narHash=sha256-p7ryWEeQfMwTB6E0wIUd5V2cFTgq%2BDRRBz2hYGnJZyA%3D (2024-03-18 12:38:16)
    └───nixpkgs-stable: github:NixOS/nixpkgs/614b4613980a522ba49f0d194531beddbb7220d3?narHash=sha256-3Eh7fhEID17pv9ZxrPwCLfqXnYP006RKzSs0JptsN84%3D (2024-03-17 17:16:56)
```

**Version**

Store path - /nix/store/amwpzhr2hs4ydwgrl90gqkkg46dm0idg-cachix-1.7.3-bin
cachix --version - 1.7.3
